name: stylish_bottom_bar
description: A collection of stylish bottom navigation bar like animated bottom bar and bubble bottom bar for flutter.
version: 0.1.5
homepage: https://github.com/MarsadMaqsood/Stylish_bottom_bar

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  
  flutter_test:
    sdk: flutter